services:
  database:
    image: mysql:8
    container_name: aepcontainerdatabase
    environment:
      MYSQL_ROOT_PASSWORD: root # Senha do usuário root
      MYSQL_DATABASE: dadosseguros # Nome do banco de dados inicial
      MYSQL_USER: secureuser # Nome do usuário do banco de dados
      MYSQL_PASSWORD: 1324 # Senha do usuário do banco de dados
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: aepcontaineradminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - "8080:8080"

volumes:
  mysql_data: